### ISSUE TITLE
🐛 Bug: env value NULL

### ISSUE THREAD

**Issue by chanhihi** [chanheki/minishell#141]
1. env value 가 NULL일 때, change value가 일어나지 않고 계속 등록됨.

2. export value가 NULL일 때, export 에서는 보이지만 env에서는 안보이는 현상 발생.

**Comment by chanhihi** [comment]
@nyj001012 2. 추가설명 export value가 NULL인 변수가 중간에 껴있으면 env에서 보이지 않는 현상
![image](https://github.com/chanheki/minishell/assets/85754295/a3225f67-3bdd-4686-b3a3-bb96770871ac)
![image](https://github.com/chanheki/minishell/assets/85754295/a50bef3d-2abd-4d9e-a4e8-58445a06657d)

**Comment by nyj001012** [comment]
예시
1.
export yena
export yena
export

-> export 현재 결과
yena
yena

2.
export yena=""

-> env 예상 결과
yena=
